aim_fit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aimfit_app.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

aimfit_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class Login(AbstractUser):
    is_trainer=models.BooleanField(default=False)
    is_user=models.BooleanField(default=False)
    is_physician=models.BooleanField(default=False)
    is_customer=models.BooleanField(default=False)

class Trainer(models.Model):
    user=models.OneToOneField(Login,on_delete=models.CASCADE,related_name='trainer',null=True,blank=True)
    name=models.CharField(max_length=50)
    age=models.IntegerField()
    address=models.TextField()
    qualification=models.CharField(max_length=50)
    achievement=models.CharField(max_length=50)
    contact_no=models.CharField(max_length=10)
    image=models.ImageField(upload_to='pic')

class Physician(models.Model):
    user=models.OneToOneField(Login,on_delete=models.CASCADE,related_name='physician',null=True,blank=True)
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    address = models.TextField()
    qualification = models.CharField(max_length=50)
    contact_no = models.CharField(max_length=10)
    image = models.ImageField(upload_to='pic')

class Equipments(models.Model):
    name=models.CharField(max_length=50)
    image=models.ImageField()
    discrition=models.TextField()

class Customer(models.Model):
    user=models.OneToOneField(Login,on_delete=models.CASCADE,related_name='customer',null=True,blank=True)
    name=models.CharField(max_length=50)
    age = models.IntegerField()
    address = models.TextField()
    contact_no = models.CharField(max_length=10)
    image = models.ImageField(upload_to='pic')

    def __str__(self):
        return self.name

class Batch(models.Model):
    name=models.CharField(max_length=50)
    time=models.TimeField()

class Complaint(models.Model):
    user=models.ForeignKey(Login,on_delete=models.CASCADE)
    complaint=models.TextField()
    reply=models.TextField(null=True,blank=True)
    date=models.DateField()

class DietPlan(models.Model):
    heading=models.CharField(max_length=50)
    diet=models.ImageField()

class Attendance(models.Model):
    name=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='attendance',null=True,blank=True)
    attendance=models.CharField(max_length=50,null=True,blank=True)
    date=models.DateField()
    time=models.TimeField()

class HealthCondition(models.Model):
    name=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='healthcondition',null=True,blank=True)
    height=models.FloatField(max_length=50)
    weight=models.FloatField(max_length=50)
    medicinconsumption=models.TextField()

class Notification(models.Model):
    date=models.DateField()
    subject=models.CharField(max_length=50)
    text=models.TextField()

class Payment(models.Model):
    name=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='payment')
    amount=models.IntegerField()
    due_date=models.DateField()
    card_no=models.IntegerField(null=True,blank=True)
    card_name=models.CharField(max_length=50,null=True,blank=True)
    cvv=models.IntegerField(null=True,blank=True)



class Chat(models.Model):
    user=models.ForeignKey(Trainer,on_delete=models.CASCADE,related_name='chat')
    message=models.TextField()
    reply=models.TextField(null=True,blank=True)

templates/trainertemp/add_healthc.html
{% extends 'trainertemp/trainer_home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-6 grid-margin stretch-card">
  <div class="card">
     {% for message in messages %}
<!--<div class="alert alert-success" role="alert">-->
<!--  Equipment is added !-->
<!--</div>-->
{% endfor %}
                <div class="card-body">
                  <h4 class="card-title">Add Health Condition update Plan</h4>
                  <p class="card-description">
                  </p>
                  <form class="forms-sample" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ health_form|crispy }}
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}

templates/trainertemp/diet_add.html
{% extends 'trainertemp/trainer_home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-6 grid-margin stretch-card">
  <div class="card">
<!--     {% for message in messages %}-->
<!--<div class="alert alert-success" role="alert">-->
<!--  Equipment is added !-->
<!--</div>-->
<!--{% endfor %}-->
                <div class="card-body">
                  <h4 class="card-title">Add New Diet Plan</h4>
                  <p class="card-description">
                    Add Diet Plans Here
                  </p>
                  <form class="forms-sample" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ diet_form|crispy }}
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}

templates/trainertemp/diet_view.html
{% extends 'trainertemp/trainer_home.html' %}
{% block content %}
<style>
  .card-deck{height : 350px; overflow-y: auto;}
</style>
<!--{% for message in messages %}-->
<!--<div class="alert alert-success" role="alert">-->
<!--    <strong>{{message}}</strong>-->
<!--</div>-->
<!--{% endfor %}-->

<!--<div class='row card-group'>-->
    {% for i in diet %}
<div class="col-4">
  <div class="card-deck">
<div class="card" style="width: 25rem;">
  <img src="{{i.diet.url}}" width="350px" height="250px" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.heading}}</h5>
  </div>
<!--  <script>-->
<!--  function del1(){-->
<!--  alert("equipment will be deleted!!")-->
<!--  }-->
<!--  </script>-->
</div>
</div>
</div>
   {% endfor %}
<!--</div>-->
{% endblock %}

templates/trainertemp/healthview.html
{% extends 'trainertemp/trainer_home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Helath Details Table</h4>
<!--                  <p class="card-description">-->
<!--                    Add class <code>.table-striped</code>-->
<!--                  </p>-->

                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>
                            #
                          </th>
                          <th>
                             Name
                          </th>
                          <th>
                            Height
                          </th>
                          <th>
                            Weight
                          </th>
                          <th>
                            Medicin Consumption
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for i in health %}
                        <tr>
                          <td>{{forloop.counter}}</td>
                          <td>{{i.name}}</td>
                          <td>{{i.height}}</td>
                          <td>{{i.weight}}</td>
                          <td>{{i.medicinconsumption}}</td>

                          </tr>
                          {% endfor %}
<!--                          <td class="py-1">-->
<!--                          </td>-->
<!--                          <td></td>-->

                      </body>
                    </table>
                  </div>

                </div>
              </div>
</div>
{% endblock %}

templates/trainertemp/prof_update.html
{% extends 'trainertemp/trainer_home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-6 grid-margin stretch-card">
  <div class="card">
     {% for message in messages %}
<!--<div class="alert alert-success" role="alert">-->
<!--  Equipment is added !-->
<!--</div>-->
{% endfor %}
                <div class="card-body">
                  <h4 class="card-title">Add Batch</h4>
                  <p class="card-description">
<!--                    you can Add New Batches Here-->
                  </p>
                  <form class="forms-sample" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ trform|crispy }}
<!--                      <div class="form-group">-->
<!--    <label for="Batchid">Batch Name</label>-->
<!--    <input type="text" class="form-control" id="Batchid" name="name">-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <label for="id_time">Batch Time</label>-->
<!--    <input type="time" class="form-control" name="time" id="id_time">-->
<!--  </div>-->
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}

templates/trainertemp/trainer_profview.html
{% extends 'trainertemp/trainer_home.html' %}
{% block content %}
<!--<style>-->
<!--  .card-deck{height : 450px; overflow-y: auto;}-->
<!--</style>-->
<div class="col-4">
  <div class="card-deck">
<div class="card" style="width: 25rem;">
  <img src="{{request.user.trainer.image.url}}" width="350px" height="250px" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Name : {{request.user.trainer.name}}</h5>
    <h5 class="card-title">Age : {{request.user.trainer.age}}</h5>
    <h5 class="card-title">Address : {{request.user.trainer.address}}</h5>
    <h5 class="card-title">Qualification : {{request.user.trainer.qualification}}</h5>
    <h5 class="card-title">Achievement : {{request.user.trainer.achievement}}</h5>
    <h5 class="card-title">Contact No : {{request.user.trainer.contact_no}}</h5>
  <a class="btn btn-primary" href="{% url 'profile_update' request.user.trainer.id %}" role="button">Update</a>

  </div>
</div>
</div>
</div>
{% endblock %}

templates/trainertemp/trainercust_view.html
{% extends 'trainertemp/trainer_home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Customers Details Table</h4>
<!--                  <p class="card-description">-->
<!--                    Add class <code>.table-striped</code>-->
<!--                  </p>-->

                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>
                             Name
                          </th>
                          <th>
                            Age
                          </th>
                          <th>
                            Address
                          </th>
                          <th>
                            Contact No
                          </th>
                          <th>
                            Image
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for i in cust %}
                        <tr>
                          <td>{{forloop.counter}}</td>
                          <td>{{i.name}}</td>
                          <td>{{i.age}}</td>
                          <td>{{i.address}}</td>
                          <td>{{i.contact_no}}</td>
                          <td><img src="{{i.image.url}}" class="rounded float-start" style="width:70px;height:60px;"></td>
<!--                          <td><form method="post" action="{% url 'physician_delete' i.id %}" onsubmit="sub1()">-->
<!--                            {% csrf_token %}-->
<!--                            <button type="submit" class="btn btn-danger">-->
<!--                          Delete-->
<!--                          </button></form></td>-->
                          </tr>
                          {% endfor %}
<!--                          <td class="py-1">-->
<!--                          </td>-->
<!--                          <td></td>-->

                      </body>
                    </table>
                  </div>
<!--                  <script>-->
<!--                    function sub1(){-->
<!--                    alert("user will be deleted!!")-->
<!--                    }-->
<!--                  </script>-->
                </div>
              </div>
</div>
{% endblock %}

templates/trainertemp/update_healthc.html
{% extends 'trainertemp/trainer_home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-6 grid-margin stretch-card">
  <div class="card">
     {% for message in messages %}
<!--<div class="alert alert-success" role="alert">-->
<!--  Equipment is added !-->
<!--</div>-->
{% endfor %}
                <div class="card-body">
                  <h4 class="card-title">Add Health Condition update Plan</h4>
                  <p class="card-description">
                  </p>
                  <form class="forms-sample" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ health|crispy }}
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}